export const discordConfig = {
	DISCORD_BOT_TOKEN: process.env.DISCORD_BOT_TOKEN,
	DISCORD_BILLING_CHANNEL_ID: process.env.DISCORD_BILLING_CHANNEL_ID,
	DISCORD_ORDER_CHANNEL_ID: process.env.DISCORD_ORDER_CHANNEL_ID,
};
